config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file,
  # see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, param: :nickname do
    resources :recipes
  end
  resources :recipes
  get '/pick', to: 'welcome#pick'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, dependent: :destroy

  def to_param
    nickname
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = view_context.current_user.recipes.new
  end

  def edit
    @recipe = view_context.current_user.recipes.find(params[:id])
  end

  def create
    @recipe = view_context.current_user.recipes.create(recipe_params)
  
    if @recipe.save
      redirect_to user_path(view_context.current_user)
    else
      render 'new'
    end
  end

  def update
    @recipe = view_context.current_user.recipes.find(params[:id])
  
    if @recipe.update(recipe_params)
      redirect_to user_path(view_context.current_user)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = view_context.current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to user_path(view_context.current_user)
  end

  private
    def recipe_params
      params.require(:recipe).permit(:title, :text)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    unless request.env['omniauth.auth'][:uid]
      flash[:danger] = '連携に失敗しました'
      redirect_to root_url
    end
    user_data = request.env['omniauth.auth']
    user = User.find_by(uid: user_data[:uid])
    if user
      view_context.log_in user
      flash[:success] = 'ログインしました'
      redirect_to root_url
    else
      new_user = User.new(
        uid: user_data[:uid],
        nickname: user_data[:info][:nickname],
        name: user_data[:info][:name],
        image: user_data[:info][:image],
      )
      if new_user.save
        view_context.log_in new_user
        flash[:success] = 'ユーザー登録成功'
      else
        flash[:danger] = '予期せぬエラーが発生しました'
      end
      redirect_to root_url
    end
  end

  def destroy
    view_context.log_out if view_context.logged_in?
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(nickname: params[:nickname])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def pick
    @picked = Recipe.order(Arel.sql('RANDOM()')).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:uid] = user.uid
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:uid]
      @current_user ||= User.find_by(uid: session[:uid])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:uid)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul>
      <li>
        <%= link_to 'ホーム', root_path %>
      </li>
      <% if logged_in? %>
      <li>
        <%= link_to 'マイページ', user_path(current_user) %>
      </li>
      <% end %>
      <li>
        <% if logged_in? %>
        <%= link_to 'ログアウト', logout_path %>
        <% else %>
        <a href="/auth/twitter">ログイン</a>
        <% end %>
      </li>
      <li>
        <a href="https://github.com/oshinko/recipicker">GitHub</a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%
      title = content_for?(:title) ? yield(:title) : 'Recipicker'
      description = content_for?(:description) ? yield(:description) : '今日のレシピをランダムピック！'
      image = request.base_url + image_path(content_for?(:image) ? yield(:image) : 'icon.png')
    %>
    <title><%= title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta name="description" content="<%= description %>">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:creator" content="@Osynco">
    <meta name="twitter:site" content="@Osynco">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:title" content="<%= title %>">
    <meta property="og:description" content="<%= description %>" />
    <meta property="og:image" content="<%= image %>">
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with model: [@user, @recipe], local: true do |form| %>
  <% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited
    this recipe from being saved:</h2>
    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/recipes/_recipe.html.erb
<h1><%= @recipe.title %></h1>
<article id="flow"></article>
<script>const RECIPES = [{ el: '#flow', text: `<%= @recipe.text %>` }]</script>

app/views/recipes/edit.html.erb
<main>
  <h1>レシピを編集</h1>
  <%= render 'form' %>
</main>

<%= render 'layouts/footer' %>

app/views/recipes/new.html.erb
<main>
  <h1>新しいレシピを登録</h1>
  <%= render 'form' %>
</main>

<%= render 'layouts/footer' %>

app/views/recipes/show.html.erb
<main>
  <%= render @recipe %>
</main>

<%= render 'layouts/footer' %>

app/views/users/show.html.erb
<main>
  <h1><%= @user.nickname %></h1>
  <img src="<%= @user.image %>" />

  <h2>Recipes</h2>
  <% if @user == current_user %>
  <p><%= link_to '新しいレシピを登録', new_recipe_path %></p>
  <% end %>
  <ul>
    <% @user.recipes.each do |recipe| %>
    <li>
      <%= recipe.title %>
      <% if @user == current_user %>
      [<%= link_to '編集', edit_recipe_path(recipe) %> |
       <%= link_to '削除', recipe_path(recipe), method: :delete, data: { confirm: '本当に削除してもいいですか？' } %>]
      <% end %>
    </li>
    <% end %>
  </ul>
</main>

<%= render 'layouts/footer' %>

app/views/welcome/index.html.erb
<main>
  <button onclick="pick()">今日のレシピをピック！</button>
</main>

<script>
function pick() {
  window.location.href = '/pick';
}
</script>

<%= render 'layouts/footer' %>

app/views/welcome/pick.html.erb
<div class="foods">
  <div class="ramen">
    <div class="donburi"></div>
    <div class="donburi-gu"></div>
    <div class="donburi-soko"></div>
  </div>
</div>

<script>
document.querySelector('.ramen').addEventListener('animationend', function() {
  this.style.visibility = 'hidden';
  window.location.href = '<%= recipe_path(@picked) %>';
});
</script>

<style>
:root {
  --donburi: #CCC;
  --donburi-gu: brown;
}
.donburi {
  width: 80px;
  height: 40px;
  border-radius: 0 0 40px 40px;
  background: var(--donburi);
}
.donburi-gu {
  width: 80px;
  height: 80px;
  transform: rotateX(75deg);
  border-radius: 50%;
  background: var(--donburi-gu);
}
.donburi-soko {
  width: 20px;
  height: 10px;
  border-radius: 25%;
  background: var(--donburi);
}
.foods {
  position: relative;
  overflow: hidden;
  width: 100vw;
  height: 100vh;
}
.foods .ramen {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  margin: auto;
  width: 80px;
  height: 68px;
  animation: donburi 2.75s linear;
  animation-iteration-count: 1;
  transform-origin: 50% 100% 0;
}
.foods .ramen .donburi {
  position: absolute;
  top: 20px;
  left: 0;
}
.foods .ramen .donburi-gu {
  position: absolute;
  top: -20px;
  left: 0;
}
.foods .ramen .donburi-soko {
  position: absolute;
  bottom: 0;
  left: 30px;
}
@keyframes donburi {
  15% {
    transform: translate(0px, 0px);
  }
  18% {
    transform: translate(0px, 16px);
  }
  21% {
    transform: translate(0px, -5px);
  }
  24% {
    transform: translate(0px, 0px);
  }
  30% {
    transform: translate(0px, 0px);
  }
  33% {
    transform: translate(0px, 16px);
  }
  36% {
    transform: translate(0px, -5px);
  }
  39% {
    transform: translate(0px, 0px);
  }
  45% {
    transform: translate(0px, 0px);
  }
  50% {
    transform: rotateZ(5deg);
  }
  55% {
    transform: rotateZ(-5deg);
  }
  60% {
    transform: rotateZ(5deg);
  }
  65% {
    transform: rotateZ(-5deg);
  }
  70% {
    transform: rotateZ(5deg);
  }
  75% {
    transform: rotateZ(-5deg);
  }
  80% {
    transform: rotateZ(5deg);
  }
  85% {
    transform: rotateZ(-5deg);
  }
  90% {
    transform: rotateZ(0deg);
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
</style>